const vulne_avg_data = [
    {
      "id": 1,
      "name": "Bluetooth",
      "Vulnerabilities": 188,
      "Up_Pa_Yes": 77,
      "Up_Pa_No": 23,
      "Avg_BM": 6.7,
      "Avg_TM": 6.2,
      "Avg_OT": 6.2,
      "Avg_IT": 6,
      "Calc_BM_TM": 0.5,
      "Calc_OT_IT": 0.2
    },
    {
      "id": 2,
      "name": "ZigBee",
      "Vulnerabilities": 9,
      "Up_Pa_Yes": 56,
      "Up_Pa_No": 44,
      "Avg_BM": 6.4,
      "Avg_TM": 6,
      "Avg_OT": 6.7,
      "Avg_IT": 5.6,
      "Calc_BM_TM": 0.4,
      "Calc_OT_IT": 1.1
    },
    {
      "id": 3,
      "name": "RFID/NFC",
      "Vulnerabilities": 23,
      "Up_Pa_Yes": 48,
      "Up_Pa_No": 52,
      "Avg_BM": 6.2,
      "Avg_TM": 5.8,
      "Avg_OT": 5.8,
      "Avg_IT": 5.7,
      "Calc_BM_TM": 0.4,
      "Calc_OT_IT": 0.1
    },
    {
      "id": 4,
      "name": "MQTT",
      "Vulnerabilities": 31,
      "Up_Pa_Yes": 74,
      "Up_Pa_No": 26,
      "Avg_BM": 6.1,
      "Avg_TM": 5.7,
      "Avg_OT": 5.7,
      "Avg_IT": 5.4,
      "Calc_BM_TM": 0.4,
      "Calc_OT_IT": 0.3
    },
    {
      "id": 5,
      "name": "CoAP",
      "Vulnerabilities": 5,
      "Up_Pa_Yes": 40,
      "Up_Pa_No": 60,
      "Avg_BM": 6.3,
      "Avg_TM": 5.8,
      "Avg_OT": 6.7,
      "Avg_IT": 5.1,
      "Calc_BM_TM": 0.5,
      "Calc_OT_IT": 1.6
    },
    {
      "id": 6,
      "name": "REST/HTTP",
      "Vulnerabilities": 207,
      "Up_Pa_Yes": 85,
      "Up_Pa_No": 15,
      "Avg_BM": 6.8,
      "Avg_TM": 6.2,
      "Avg_OT": 6,
      "Avg_IT": 6.3,
      "Calc_BM_TM": 0.6,
      "Calc_OT_IT": -0.3
    },
    {
      "id": 7,
      "name": "JMS",
      "Vulnerabilities": 29,
      "Up_Pa_Yes": 86,
      "Up_Pa_No": 14,
      "Avg_BM": 7.3,
      "Avg_TM": 6.7,
      "Avg_OT": 6.7,
      "Avg_IT": 6.8,
      "Calc_BM_TM": 0.6,
      "Calc_OT_IT": -0.1
    },
    {
      "id": 8,
      "name": "AMQP",
      "Vulnerabilities": 57,
      "Up_Pa_Yes": 91,
      "Up_Pa_No": 9,
      "Avg_BM": 6.4,
      "Avg_TM": 5.8,
      "Avg_OT": 6,
      "Avg_IT": 5.5,
      "Calc_BM_TM": 0.6,
      "Calc_OT_IT": 0.5
    },
    {
      "id": 9,
      "name": "DDS",
      "Vulnerabilities": 3,
      "Up_Pa_Yes": 100,
      "Up_Pa_No": 0,
      "Avg_BM": 3.2,
      "Avg_TM": 2.9,
      "Avg_OT": 3.5,
      "Avg_IT": 2.2,
      "Calc_BM_TM": 0.3,
      "Calc_OT_IT": 1.3
    },
    {
      "id": 10,
      "name": "XMPP",
      "Vulnerabilities": 86,
      "Up_Pa_Yes": 93,
      "Up_Pa_No": 7,
      "Avg_BM": 6.2,
      "Avg_TM": 5.6,
      "Avg_OT": 5.7,
      "Avg_IT": 5.7,
      "Calc_BM_TM": 0.6,
      "Calc_OT_IT": 0
    },
    {
      "id": 11,
      "name": "WebSocket",
      "Vulnerabilities": 62,
      "Up_Pa_Yes": 84,
      "Up_Pa_No": 16,
      "Avg_BM": 6.8,
      "Avg_TM": 6.2,
      "Avg_OT": 6.2,
      "Avg_IT": 5.9,
      "Calc_BM_TM": 0.6,
      "Calc_OT_IT": 0.3
    },
    {
      "id": 12,
      "name": "Modbus",
      "Vulnerabilities": 40,
      "Up_Pa_Yes": 80,
      "Up_Pa_No": 20,
      "Avg_BM": 7.8,
      "Avg_TM": 7,
      "Avg_OT": 7.1,
      "Avg_IT": 6.7,
      "Calc_BM_TM": 0.8,
      "Calc_OT_IT": 0.4
    },
    {
      "id": 13,
      "name": "Siemens S7",
      "Vulnerabilities": 46,
      "Up_Pa_Yes": 93,
      "Up_Pa_No": 7,
      "Avg_BM": 6.4,
      "Avg_TM": 5.8,
      "Avg_OT": 6.6,
      "Avg_IT": 5,
      "Calc_BM_TM": 0.6,
      "Calc_OT_IT": 1.6
    },
    {
      "id": 14,
      "name": "EtherNet/IP",
      "Vulnerabilities": 22,
      "Up_Pa_Yes": 50,
      "Up_Pa_No": 50,
      "Avg_BM": 7.3,
      "Avg_TM": 6.8,
      "Avg_OT": 7.7,
      "Avg_IT": 6,
      "Calc_BM_TM": 0.5,
      "Calc_OT_IT": 1.7
    },
    {
      "id": 15,
      "name": "Hart/IP",
      "Vulnerabilities": 5,
      "Up_Pa_Yes": 60,
      "Up_Pa_No": 40,
      "Avg_BM": 6.3,
      "Avg_TM": 5.9,
      "Avg_OT": 6.5,
      "Avg_IT": 5.3,
      "Calc_BM_TM": 0.4,
      "Calc_OT_IT": 1.2
    },
    {
      "id": 16,
      "name": "PROFINET",
      "Vulnerabilities": 30,
      "Up_Pa_Yes": 97,
      "Up_Pa_No": 3,
      "Avg_BM": 7.13,
      "Avg_TM": 6.49,
      "Avg_OT": 7.4,
      "Avg_IT": 5.5,
      "Calc_BM_TM": 0.64,
      "Calc_OT_IT": 1.9
    },
    {
      "id": 17,
      "name": "BACnet",
      "Vulnerabilities": 16,
      "Up_Pa_Yes": 100,
      "Up_Pa_No": 0,
      "Avg_BM": 6.7,
      "Avg_TM": 6.3,
      "Avg_OT": 5.8,
      "Avg_IT": 6.3,
      "Calc_BM_TM": 0.4,
      "Calc_OT_IT": -0.5
    },
    {
      "id": 18,
      "name": "Niagara AX",
      "Vulnerabilities": 7,
      "Up_Pa_Yes": 100,
      "Up_Pa_No": 0,
      "Avg_BM": 6.8,
      "Avg_TM": 6.1,
      "Avg_OT": 5.7,
      "Avg_IT": 6.2,
      "Calc_BM_TM": 0.7,
      "Calc_OT_IT": -0.5
    },
    {
      "id": 19,
      "name": "OPC-DA",
      "Vulnerabilities": 52,
      "Up_Pa_Yes": 92,
      "Up_Pa_No": 8,
      "Avg_BM": 6.8,
      "Avg_TM": 6.3,
      "Avg_OT": 6.6,
      "Avg_IT": 5.8,
      "Calc_BM_TM": 0.5,
      "Calc_OT_IT": 0.8
    },
    {
      "id": 20,
      "name": "OPC-UA",
      "Vulnerabilities": 16,
      "Up_Pa_Yes": 100,
      "Up_Pa_No": 0,
      "Avg_BM": 6.6,
      "Avg_TM": 6,
      "Avg_OT": 6.3,
      "Avg_IT": 5.3,
      "Calc_BM_TM": 0.6,
      "Calc_OT_IT": 1
    },
    {
      "id": 21,
      "name": "DNP3",
      "Vulnerabilities": 58,
      "Up_Pa_Yes": 97,
      "Up_Pa_No": 3,
      "Avg_BM": 6.3,
      "Avg_TM": 5.7,
      "Avg_OT": 6.7,
      "Avg_IT": 4.6,
      "Calc_BM_TM": 0.6,
      "Calc_OT_IT": 2.1
    },
    {
      "id": 22,
      "name": "ANSI c12.22",
      "Vulnerabilities": 3,
      "Up_Pa_Yes": 100,
      "Up_Pa_No": 0,
      "Avg_BM": 5.6,
      "Avg_TM": 5.1,
      "Avg_OT": 5.1,
      "Avg_IT": 5.1,
      "Calc_BM_TM": 0.5,
      "Calc_OT_IT": 0
    },
    {
      "id": 23,
      "name": "IEC61850",
      "Vulnerabilities": 19,
      "Up_Pa_Yes": 100,
      "Up_Pa_No": 0,
      "Avg_BM": 6.32,
      "Avg_TM": 5.66,
      "Avg_OT": 5.81,
      "Avg_IT": 5.19,
      "Calc_BM_TM": 0.66,
      "Calc_OT_IT": 0.62
    },
    {
      "id": 24,
      "name": "IEC 104",
      "Vulnerabilities": 15,
      "Up_Pa_Yes": 100,
      "Up_Pa_No": 0,
      "Avg_BM": 6.96,
      "Avg_TM": 6.27,
      "Avg_OT": 6.6,
      "Avg_IT": 5.76,
      "Calc_BM_TM": 0.69,
      "Calc_OT_IT": 0.84
    },
    {
      "id": 25,
      "name": "ICCP",
      "Vulnerabilities": 7,
      "Up_Pa_Yes": 100,
      "Up_Pa_No": 0,
      "Avg_BM": 5.41,
      "Avg_TM": 4.87,
      "Avg_OT": 6.09,
      "Avg_IT": 3.69,
      "Calc_BM_TM": 0.54,
      "Calc_OT_IT": 2.4
    }
];